# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_type',
            field=models.CharField(choices=[('billing', 'Cobrança'), ('shipping', 'Entrega')], max_length=120),
        ),
    ]
