# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-25 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_usercheckout_braintree_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Criado'), ('paid', 'Pago'), ('shipped', 'Finalizado')], default='created', max_length=20),
        ),
    ]
