# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_cart_tax_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=3, default=0.085, max_digits=4),
        ),
    ]
