# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20161208_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_category', to='products.Category'),
        ),
    ]
